on: [push]

env:
  RUST_VERSION: 1.70.0
  RUST_VERSION_NIGHTLY: nightly-2023-06-12
  COVERAGE_THRESHOLD: 95

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_VERSION}}
          profile: minimal
          override: true
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test

  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_VERSION_NIGHTLY}}
          profile: minimal
          components: llvm-tools-preview
          override: true
      - name: Install grcov
        run: cargo install grcov --debug
      - name: Run coverage
        run: bash .github/workflows/scripts/run_coverage.sh
      - name: Upload coverage report on GitHub
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./
          if-no-files-found: error
          retention-days: 1
      - name: Check coverage threshold
        run: bash .github/workflows/scripts/check_coverage.sh
